import { set, wait } from 'cerebral/operators';
import { state, props } from 'cerebral/tags';

import { VIEWS } from 'common/constants';

// Action
function shoutIt({state, props}) {
  return {
    message: `${props.message}!!!`
  }
}

export default {
  state: {
    currentView: VIEWS.PLAYERS,
    subTitle: 'Some subtitle!'
  },
  signals: {
    changeSubtitle: [
      shoutIt,
      set(state`app.subTitle`, props`message`), // simple action generated by operator 'set'
      wait(4000), // simple action generated by operator 'wait'
      set(state`app.subTitle`, null) // simple action generated by operator 'set'
    ],
    notFoundRouted: [
      set(state`app.currentView`, VIEWS.NOT_FOUND)
    ]
  }
};
